#define NO_ERROR			0
#define PARAMETERS_OUT_OF_BOUNDS	1
#define ORIGIN_SAME_AS_DESTINATION	2
#define ORIGIN_SPACE_EMPTY		3
#define MOVING_OPPOSING_PIECE		4
#define MOVING_ONTO_OWN_PIECE		5
#define INVALID_MOVE			6
#define MOVING_INTO_CHECK		7
